Set outputLength correctly on open ended range requests to encryptedBlobStore
gaul/s3proxy pull request #706
Opened 2024-10-11 12:32 UTC by ptemarvelde

This resolves https://github.com/gaul/s3proxy/issues/698.

Open ended ranged requests to encrypted files resulted in incorrect Content-Length headers in the response because of a bug in the Decryption class.

In EncryptedBloBStore the length is set to `-1` by default. On open-ended ranged GET requests this value is passed to the `Decryption` constructor. After this change the `outputLength` is set correctly in this constructor.

https://github.com/gaul/s3proxy/blob/master/src/main/java/org/gaul/s3proxy/EncryptedBlobStore.java#L375

@gaul The tests pass (locally) but I have not spend enough time with this codebase to reason about whether this change will break anything else (which is currently untested). Is this a reasonable solution for https://github.com/gaul/s3proxy/issues/69?

2024-10-11 22:20 UTC, gaul commented
Can you add a unit test that demonstrates this problem?  I wonder how does encryption work for range requests?  I would imagine that S3Proxy needs to decrypt either the entire object or at least whatever the encryption block size is.  CC @FlorinPeter who wrote the original code.

2024-10-12 11:59 UTC, ptemarvelde commented
Partial decryption is already extensively tested in `EncryptedBlobStoreTest`, see [`testReadPartial`](https://github.com/gaul/s3proxy/blob/33b3427256a5f4ae46d34177337a5e216d0bbd41/src/test/java/org/gaul/s3proxy/EncryptedBlobStoreTest.java#L564), [`testMultiPartReadPartial`](https://github.com/gaul/s3proxy/blob/33b3427256a5f4ae46d34177337a5e216d0bbd41/src/test/java/org/gaul/s3proxy/EncryptedBlobStoreTest.java#L670) and [`testMultiPartReadTail`](https://github.com/gaul/s3proxy/blob/33b3427256a5f4ae46d34177337a5e216d0bbd41/src/test/java/org/gaul/s3proxy/EncryptedBlobStoreTest.java#L721). Both `testMultiPartRead*` tests test the situation where no explicit end byte is given. 

As confirmed by these tests, the content s3proxy returns for encrypted blobs for any ranged request is correct. Just the ContentLength response header is incorrect in the described case, due to the bug in the `Encryption` class. I have extended one of the unittests to verify this behavior and show the content length is set correctly now.

2024-10-16 04:08 UTC, gaul requested changes
Thanks for the explanation!  Please fit the nits so I can merge this.

2024-10-16 04:08 UTC, gaul commented on src/test/java/org/gaul/s3proxy/EncryptedBlobStoreLiveTest.java
> +        assertThat((long) partialContent.length()).isEqualTo(object.getMetadata().getContentMetadata().getContentLength());
Can you address the overlong lines Checkstyle violation?

2024-10-16 17:44 UTC, merged

2024-10-16 17:44 UTC, gaul commented
Thank you for your contribution and explanation @ptemarvelde!  I didn't write this middleware and don't have a good understanding how it works.